### ISSUE TITLE
Checklist of shallow water implementation

### ISSUE THREAD

**Issue by andrewwinters5000** [trixi-framework/TrixiShallowWater.jl#117]
This issue serves to collect what features / mesh types are available for the shallow water system:

- [x] TreeMesh1D (see trixi-framework/Trixi.jl#1118)
- [x] TreeMesh2D (see trixi-framework/Trixi.jl#890)
- [x] StructuredMesh2D
- [x] UnstructuredMesh2D
- [ ] P4estMesh2D
- [x] Flux differencing form
- [ ] AMR (for this feature the issue of well-balancedness becomes interesting)
- [x] Shock capturing (related to trixi-framework/Trixi.jl#736)
- [x] Hydrostatic reconstruction (see https://github.com/trixi-framework/Trixi.jl/pull/844#discussion_r714830685 and trixi-framework/Trixi.jl#1133 )
- [ ] Handling wet/dry flow regions (special flavor of positivity preservation)

**Comment by andrewwinters5000** [comment]
All the features are available (at least experimentally). There is issue #77 that concerns improving the AMR and mortar capabilities.
